name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Obtener número de etiqueta (tag)
        id: get_tag
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')"

      - name: Construir imagen de Docker
        run: |
          docker build -t valentinochiappanni07/frontend:${{ steps.get_tag.outputs.tag }} .
          docker push valentinochiappanni07/frontend:${{ steps.get_tag.outputs.tag }}

      - name: Logout de Docker Hub
        run: docker logout
